server:
  port: 8083
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/LMS"
    username: root
    password: abc123-
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://127.0.0.1:3000,https://localhost:3000}

# Logging
#logging:
#  level:
#    com.app.lms: INFO
#    org.springframework.security: WARN
#    org.hibernate: WARN
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
app:
  jwt:
    secret: 2nIXqNA3pjyrUvlwxmd8+lbTa/0OWCDgBUg+FXp9Oc5orQmXKmVDXeXWt442G0vX
# Development profile settings
---
spring:
  config:
    activate:
      on-profile: development

cors:
  allowed-origins: "http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001"

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.security: DEBUG

